# Generated by Django 5.0.7 on 2024-08-29 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediaryCloudAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_agent_name', models.CharField(max_length=255)),
                ('tin_no', models.CharField(max_length=15)),
                ('vrn_registered', models.BooleanField()),
                ('vrn_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('company_email', models.EmailField(max_length=254)),
                ('tin_document', models.FileField(blank=True, null=True, upload_to='documents/tin/')),
                ('tira_cert', models.FileField(blank=True, null=True, upload_to='documents/tira/')),
                ('brela_document', models.FileField(blank=True, null=True, upload_to='documents/brela/')),
                ('vrn_document', models.FileField(blank=True, null=True, upload_to='documents/vrn/')),
            ],
        ),
        migrations.CreateModel(
            name='CloudAccessEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_access_email', models.EmailField(max_length=254)),
                ('intermediary_cloud_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_access_emails', to='formsubmission.intermediarycloudaccess')),
            ],
        ),
        migrations.CreateModel(
            name='CCEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_email', models.EmailField(max_length=254)),
                ('intermediary_cloud_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_emails', to='formsubmission.intermediarycloudaccess')),
            ],
        ),
    ]
